INSERT INTO public.questions (subject, question, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('Zoology','Which organelle is primarily responsible for ATP production in aerobic eukaryotic cells?','Lysosome','Mitochondrion','Ribosome','Golgi apparatus','B','Mitochondria carry out oxidative phosphorylation.'),
('Zoology','The fluid mosaic model describes the structure of the:','Plasma membrane','Nucleus','Ribosome','Cell wall','A','It describes a phospholipid bilayer with embedded proteins.'),
('Zoology','During meiosis, crossing over normally occurs during:','Metaphase II','Prophase I','Telophase I','Anaphase II','B','Homologous chromosomes exchange segments during prophase I.'),
('Zoology','The normal pacemaker of the human heart is the:','Purkinje fibre','Bundle of His','AV node','SA node','D','The sinoatrial node normally initiates cardiac impulses.'),
('Zoology','Most filtered glucose is reabsorbed in the:','Distal convoluted tubule','Proximal convoluted tubule','Loop of Henle','Collecting duct','B','The PCT reabsorbs nearly all filtered glucose under normal conditions.'),
('Zoology','Which hormone lowers blood glucose concentration?','Adrenaline','Cortisol','Glucagon','Insulin','D','Insulin promotes glucose uptake and storage.'),
('Zoology','Natural selection acts directly on:','Allele names','Taxonomic ranks','Chromosome numbers only','Phenotypes','D','Selection acts on expressed traits; allele frequencies change across generations.'),
('Botany','The first trophic level is occupied mainly by:','Secondary consumers','Primary consumers','Producers','Decomposers','C','Producers form the base of food chains.'),
('Botany','The main site of photosynthesis in a leaf mesophyll cell is the:','Nucleus','Vacuole','Chloroplast','Golgi body','C','Chloroplasts contain chlorophyll and photosynthetic machinery.'),
('Botany','Stomatal opening is most directly controlled by changes in:','Xylem lignin','Pollen number','Root cap size','Guard-cell turgor','D','Guard-cell turgor determines stomatal aperture.'),
('Botany','Water is transported mainly through:','Epidermis','Phloem','Xylem','Cambium','C','Xylem conducts water and mineral ions upward.'),
('Zoology','Animals with a notochord at least during development belong to:','Annelida','Chordata','Mollusca','Arthropoda','B','A notochord is a defining chordate feature.'),
('Botany','Bacteria are generally classified as:','Prions','Viruses','Prokaryotes','Eukaryotes','C','Bacteria lack a membrane-bound nucleus.'),
('Chemistry','The number of protons in an atom is its:','Atomic number','Valency','Mass number','Neutron number','A','Atomic number equals proton number.'),
('Chemistry','A bond formed by sharing electron pairs is a:','Covalent bond','Hydrogen bond','Metallic bond','Ionic bond','A','Covalent bonds involve shared electron pairs.'),
('Chemistry','For an exothermic reaction at constant pressure, ∆H is generally:','Positive','Negative','Zero always','Undefined','B','Heat is released, giving negative enthalpy change.'),
('Chemistry','A catalyst changes the equilibrium constant by:','Increasing it','Making it zero','Decreasing it','Not changing it','D','A catalyst accelerates both forward and reverse reactions.'),
('Chemistry','At 25°C, a neutral aqueous solution has pH approximately:','14','0','5','7','D','At 25°C, [H+] = [OH−] = 10^-7 M.'),
('Chemistry','The functional group of an alcohol is:','−CO−','−COOH','−CHO','−OH','D','Alcohols contain a hydroxyl group.'),
('Chemistry','The general formula of an alkene with one double bond in an open chain is:','CnHn','CnH2n','CnH2n−2','CnH2n+2','B','Acyclic monoalkenes follow CnH2n.'),
('Chemistry','Oxidation occurs at the:','Anode','Salt bridge only','Cathode','Voltmeter','A','Oxidation is defined as loss of electrons and occurs at the anode.'),
('Chemistry','The most electronegative element is:','Fluorine','Oxygen','Nitrogen','Chlorine','A','Fluorine has the highest electronegativity.'),
('Chemistry','Molarity is defined as moles of solute per:','kg solution','Litre of solution','mL solvent','kg solvent','B','Molarity uses litres of final solution.'),
('Chemistry','The rate of a reaction generally increases with temperature because more molecules:','Become inert','Have lower energy','Lose collisions','Exceed activation energy','D','A larger fraction has energy at or above activation energy.'),
('Chemistry','Reduction corresponds to:','Loss of protons only','Loss of electrons','Gain of electrons','Gain of neutrons','C','Reduction is gain of electrons.'),
('Physics','The SI unit of force is:','Pascal','Newton','Watt','Joule','B','One newton is kg·m·s−2.'),
('Physics','If velocity is constant, acceleration is:','Zero','Maximum','Infinite','Negative always','A','Acceleration is the rate of change of velocity.'),
('Physics','Work done by a constant force parallel to displacement is:','Fs','F/s','s/F','F+s','A','W = Fs when force and displacement are parallel.'),
('Physics','Near Earth''s surface, acceleration due to gravity is approximately:','98 m/s²','9.8 m/s²','980 m/s²','0.98 m/s²','B','The commonly used value is about 9.8 m/s².'),
('Chemistry','The first law of thermodynamics expresses conservation of:','Energy','Charge','Momentum only','Mass only','A','Energy is conserved.'),
('Physics','The speed of a wave equals:','f+λ','fλ','λ/f','f/λ','B','v = fλ.'),
('Physics','A convex lens can form a real inverted image when the object is:','Between lens and focus','Exactly at optical centre only','Beyond focal point','Nowhere','C','For an object beyond F, a convex lens can form a real inverted image.'),
('Physics','The SI unit of electric charge is:','Tesla','Coulomb','Volt','Ohm','B','Charge is measured in coulombs.'),
('Physics','Ohm''s law is:','V=I/R','V=I+R','V=IR','V=R/I','C','For an ohmic conductor at constant conditions, V = IR.'),
('Physics','The SI unit of magnetic flux density is:','Weber','Henry','Tesla','Farad','C','Magnetic flux density B is measured in tesla.'),
('Physics','The photoelectric effect supports the particle nature of:','Light','Matter only','Sound','Heat only','A','Photoelectric observations are explained by photons.'),
('Physics','An alpha particle is the nucleus of:','Hydrogen','Carbon','Helium','Neutronium','C','It contains two protons and two neutrons.'),
('MAT','Choose the word closest in meaning to ''rapid''.','Weak','Swift','Late','Slow','B','Rapid means fast or swift.'),
('MAT','Choose the word opposite in meaning to ''scarce''.','Rare','Limited','Abundant','Small','C','Abundant means plentiful.'),
('MAT','What is 15% of 200?','15','30','40','20','B','0.15 × 200 = 30.'),
('MAT','If 3x = 24, x equals:','6','9','8','12','C','Divide both sides by 3.'),
('MAT','Find the next number: 2, 4, 8, 16, __.','32','30','20','24','A','Each term is doubled.'),
('MAT','If all doctors are graduates and some graduates are researchers, which statement must be true?','No doctors are researchers','All doctors are graduates','All doctors are researchers','All researchers are doctors','B','The first premise guarantees doctors are graduates.'),
('MAT','A cube has how many faces?','8','12','4','6','D','A cube has six square faces.'),
('MAT','Which figure property remains unchanged under rotation?','Orientation on page','Top position','Left position','Number of sides','D','Rotation changes orientation but not the number of sides.'),
('Physics','A net force of 6 N acts on a 2 kg object. Its acceleration is:','5 m/s²','6 m/s²','0.67 m/s²','3 m/s²','D','Using F = ma, a = F/m.'),
('Zoology','How many chromosomes are present in a normal human somatic cell?','23','46','92','44','B','Normal human somatic cells contain 46 chromosomes (23 pairs).'),
('Physics','If the frequency of a wave is 5 Hz and its wavelength is 3 m, its speed is:','8 m/s','15 m/s','0.60 m/s','1.67 m/s','B','v = fλ.'),
('Physics','Which particle carries a negative elementary charge?','Proton','Electron','Neutron','Alpha particle','B','The electron has charge −e.'),
('Zoology','Which biomolecule is the primary structural component of the plasma membrane?','Phospholipid','DNA','Starch','Cellulose','A','The membrane is primarily a phospholipid bilayer with proteins.'),
('Chemistry','A strong acid in water is generally characterized by:','No H+ formation','Only covalent molecules','No ionization','Near-complete ionization','D','Strong acids dissociate extensively in aqueous solution.'),
('MAT','If BOOK is coded as CPPL by shifting each letter one position forward, how is CAT coded?','DBT','CBU','DZS','DBU','D','Each letter is shifted one position forward: C→D, A→B, T→U.'),
('Chemistry','If a solution contains 10 mol of solute in 9 L of solution, its molarity is:','0.90 M','1.11 M','90.00 M','19.00 M','B','Molarity = moles/volume = 10/9 = 1.11 M.'),
('Physics','If the frequency of a wave is 7 Hz and its wavelength is 3 m, its speed is:','0.43 m/s','10 m/s','2.33 m/s','21 m/s','D','v = fλ.'),
('Chemistry','If a solution contains 18 mol of solute in 6 L of solution, its molarity is:','24.00 M','0.33 M','108.00 M','3.00 M','D','Molarity = moles/volume = 18/6 = 3.00 M.'),
('Physics','A net force of 45 N acts on a 9 kg object. Its acceleration is:','14 m/s²','1.80 m/s²','45 m/s²','5 m/s²','D','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 7 mol of solute in 3 L of solution, its molarity is:','0.43 M','10.00 M','21.00 M','2.33 M','D','Molarity = moles/volume = 7/3 = 2.33 M.'),
('Physics','A net force of 48 N acts on a 8 kg object. Its acceleration is:','6 m/s²','1.33 m/s²','14 m/s²','48 m/s²','A','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 15 mol of solute in 11 L of solution, its molarity is:','1.36 M','26.00 M','165.00 M','0.73 M','A','Molarity = moles/volume = 15/11 = 1.36 M.'),
('Physics','A net force of 49 N acts on a 7 kg object. Its acceleration is:','49 m/s²','14 m/s²','7 m/s²','1.00 m/s²','C','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 4 mol of solute in 8 L of solution, its molarity is:','0.50 M','2.00 M','12.00 M','32.00 M','A','Molarity = moles/volume = 4/8 = 0.50 M.'),
('Physics','A net force of 48 N acts on a 6 kg object. Its acceleration is:','14 m/s²','8 m/s²','48 m/s²','0.75 m/s²','B','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 12 mol of solute in 5 L of solution, its molarity is:','0.42 M','60.00 M','2.40 M','17.00 M','C','Molarity = moles/volume = 12/5 = 2.40 M.'),
('Physics','A net force of 10 N acts on a 5 kg object. Its acceleration is:','2.50 m/s²','2 m/s²','10 m/s²','7 m/s²','B','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 20 mol of solute in 2 L of solution, its molarity is:','0.10 M','22.00 M','40.00 M','10.00 M','D','Molarity = moles/volume = 20/2 = 10.00 M.'),
('Physics','A net force of 12 N acts on a 4 kg object. Its acceleration is:','1.33 m/s²','3 m/s²','7 m/s²','12 m/s²','B','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 9 mol of solute in 10 L of solution, its molarity is:','19.00 M','0.90 M','90.00 M','1.11 M','B','Molarity = moles/volume = 9/10 = 0.90 M.'),
('Physics','A net force of 12 N acts on a 3 kg object. Its acceleration is:','4 m/s²','12 m/s²','0.75 m/s²','7 m/s²','A','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 17 mol of solute in 7 L of solution, its molarity is:','0.41 M','2.43 M','119.00 M','24.00 M','B','Molarity = moles/volume = 17/7 = 2.43 M.'),
('Physics','A net force of 10 N acts on a 2 kg object. Its acceleration is:','10 m/s²','5 m/s²','0.40 m/s²','7 m/s²','B','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 6 mol of solute in 4 L of solution, its molarity is:','0.67 M','24.00 M','1.50 M','10.00 M','C','Molarity = moles/volume = 6/4 = 1.50 M.'),
('Physics','A net force of 63 N acts on a 9 kg object. Its acceleration is:','16 m/s²','1.29 m/s²','7 m/s²','63 m/s²','C','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 3 mol of solute in 9 L of solution, its molarity is:','12.00 M','0.33 M','27.00 M','3.00 M','B','Molarity = moles/volume = 3/9 = 0.33 M.'),
('Physics','A net force of 64 N acts on a 8 kg object. Its acceleration is:','1.00 m/s²','16 m/s²','64 m/s²','8 m/s²','D','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 11 mol of solute in 6 L of solution, its molarity is:','66.00 M','17.00 M','1.83 M','0.55 M','C','Molarity = moles/volume = 11/6 = 1.83 M.'),
('Physics','A net force of 14 N acts on a 7 kg object. Its acceleration is:','2 m/s²','14 m/s²','9 m/s²','3.50 m/s²','A','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 19 mol of solute in 3 L of solution, its molarity is:','22.00 M','57.00 M','6.33 M','0.16 M','C','Molarity = moles/volume = 19/3 = 6.33 M.'),
('Physics','A net force of 18 N acts on a 6 kg object. Its acceleration is:','9 m/s²','18 m/s²','2.00 m/s²','3 m/s²','D','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 8 mol of solute in 11 L of solution, its molarity is:','1.38 M','0.73 M','88.00 M','19.00 M','B','Molarity = moles/volume = 8/11 = 0.73 M.'),
('Physics','A net force of 20 N acts on a 5 kg object. Its acceleration is:','20 m/s²','4 m/s²','9 m/s²','1.25 m/s²','B','Using F = ma, a = F/m.'),
('Chemistry','If a solution contains 16 mol of solute in 8 L of solution, its molarity is:','2.00 M','24.00 M','0.50 M','128.00 M','A','Molarity = moles/volume = 16/8 = 2.00 M.'),
('Physics','A net force of 20 N acts on a 4 kg object. Its acceleration is:','20 m/s²','0.80 m/s²','9 m/s²','5 m/s²','D','Using F = ma, a = F/m.');